name: sloc
version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - base
  - bytestring
  - streaming

library:
  source-dirs: src
  exposed-modules:
    - Streaming.Filesystem
  dependencies:
    - extra
    - unix

executables:
  sloc:
    main: Main.hs
    dependencies:
      - containers
      - directory
      - extra
      - filepath
      - foldl
      - sloc
      - unix
    ghc-options: -O2
